"""Shared fixtures for admin document API tests."""

from __future__ import annotations

import asyncio
import shutil
import subprocess
import uuid
from datetime import UTC, datetime
from unittest.mock import AsyncMock, MagicMock

import pytest
from databases import Database
from fastapi.testclient import TestClient

from cafetera_admin.config import AdminSettings
from cafetera_admin.main import create_app
from cafetera_core.storage.database import init_db
from cafetera_core.storage.document_repo import DocumentRepository
from cafetera_core.storage.models import DocumentRecord, DocumentStatus


def _is_docker_available() -> bool:
    if not shutil.which("docker"):
        return False
    try:
        r = subprocess.run(["docker", "info"], capture_output=True, timeout=5)
        return r.returncode == 0
    except Exception:
        return False


DOCKER_AVAILABLE = _is_docker_available()


def pytest_configure(config):
    config.addinivalue_line(
        "markers", "requires_docker: tests that need Docker (Testcontainers)",
    )
    status = "available" if DOCKER_AVAILABLE else "NOT available -- tests skipped"
    print(f"\nDocker: {status}")

TEST_API_KEY = "test-secret-key-12345"


def _make_record(**overrides) -> DocumentRecord:
    now = datetime.now(UTC)
    defaults = {
        "id": 0,  # Will be auto-generated by database
        "document_id": uuid.uuid4().hex,
        "filename": "test.docx",
        "title": "Test document",
        "s3_key": "documents/test.docx",
        "mime_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "size_bytes": 12345,
        "status": DocumentStatus.completed,
        "is_search_enabled": True,
        "error": None,
        "created_at": now,
        "updated_at": now,
        "indexed_at": now,
        "chunk_count": 5,
    }
    defaults.update(overrides)
    return DocumentRecord(**defaults)


# ── fixtures ──────────────────────────────────────────────────────


@pytest.fixture(scope="session")
def pg_container():
    """Provide a PostgreSQL Testcontainer for the test session."""
    from testcontainers.postgres import PostgresContainer

    if not DOCKER_AVAILABLE:
        pytest.skip("Docker is not running")
    with PostgresContainer(
        "postgres:16-alpine", username="test", password="test", dbname="test"
    ) as pg:
        yield pg


@pytest.fixture()
async def test_db(pg_container):
    """Create a test PostgreSQL database connection with clean tables."""
    raw_url = pg_container.get_connection_url()
    # get_connection_url() returns postgresql+psycopg2://...
    # databases[asyncpg] needs postgresql://... or postgresql+asyncpg://...
    url = raw_url.replace("postgresql+psycopg2", "postgresql")
    db = Database(url)
    await db.connect()
    # Clean tables before each test for isolation
    await db.execute(query="DROP TABLE IF EXISTS category_files CASCADE")
    await db.execute(query="DROP TABLE IF EXISTS documents CASCADE")
    await init_db(db)
    yield db
    await db.disconnect()


@pytest.fixture()
def settings(pg_container):
    """Create settings with Testcontainers PostgreSQL URL."""
    raw_url = pg_container.get_connection_url()
    # get_connection_url() returns postgresql+psycopg2://...
    # databases[asyncpg] needs postgresql://... or postgresql+asyncpg://...
    url = raw_url.replace("postgresql+psycopg2", "postgresql")
    return AdminSettings(
        admin_api_key=TEST_API_KEY,
        database_url=url,
        s3_endpoint_url="http://localhost:9000",
        s3_access_key="minioadmin",
        s3_secret_key="minioadmin",
        s3_bucket="test-bucket",
        qdrant_url="http://localhost:6333",
        _env_file=None,
    )


@pytest.fixture()
def mock_qdrant():
    client = AsyncMock()
    client.delete = AsyncMock()
    client.set_payload = AsyncMock()
    client.count = AsyncMock(return_value=AsyncMock(count=0))
    client.close = AsyncMock()
    client.upsert = AsyncMock()
    client.collection_exists = AsyncMock(return_value=True)
    client.create_collection = AsyncMock()
    return client


@pytest.fixture()
def mock_embeddings():
    return MagicMock()


@pytest.fixture()
def mock_s3():
    """Mock S3Storage with async methods."""
    s3 = MagicMock()
    s3.upload = AsyncMock()
    s3.download = AsyncMock(return_value=b"file content here")
    s3.delete = AsyncMock()
    s3.exists = AsyncMock(return_value=False)
    s3.open = AsyncMock()
    s3.close = AsyncMock()
    return s3


@pytest.fixture()
def mock_qa_service():
    """Mock QAService with invalidate_document_chain_cache method."""
    qa = MagicMock()
    qa.invalidate_document_chain_cache = MagicMock()
    return qa


@pytest.fixture()
def app(settings, mock_qdrant, mock_embeddings, mock_s3, mock_qa_service):
    """Create a test app with mocked Qdrant, embeddings, S3, and QA service.

    Uses a test lifespan that creates its own DB connection in the
    TestClient event loop to avoid cross-event-loop asyncpg issues.
    """
    from contextlib import asynccontextmanager

    from databases import Database as _Database

    from cafetera_admin.domain.document_service import DocumentService
    from cafetera_core.storage.database import init_db as _init_db
    from cafetera_core.storage.document_repo import DocumentRepository as _DocRepo

    @asynccontextmanager
    async def _test_lifespan(_app):
        db = _Database(settings.database_url)
        await db.connect()
        # Clean tables for test isolation
        await db.execute(
            query="DROP TABLE IF EXISTS category_files CASCADE"
        )
        await db.execute(
            query="DROP TABLE IF EXISTS documents CASCADE"
        )
        await _init_db(db)

        repo = _DocRepo(db)
        service = DocumentService(
            repo=repo,
            qdrant_client=mock_qdrant,
            embeddings=mock_embeddings,
            collection_name="test_collection",
        )

        _app.state.doc_repo = repo
        _app.state.doc_service = service
        _app.state.qdrant_client = mock_qdrant
        _app.state.embeddings = mock_embeddings
        _app.state.s3 = mock_s3
        _app.state.indexing_semaphore = asyncio.Semaphore(2)
        _app.state.qa_service = mock_qa_service

        yield

        await db.disconnect()

    application = create_app(settings)
    application.router.lifespan_context = _test_lifespan

    return application


@pytest.fixture()
def client(app):
    with TestClient(app, raise_server_exceptions=False) as c:
        yield c


@pytest.fixture()
def auth_cookies():
    return {"admin_session": TEST_API_KEY}


@pytest.fixture()
def auth_client(app, auth_cookies):
    """Authenticated client with cookies set on the instance."""
    with TestClient(app, raise_server_exceptions=False) as c:
        for key, value in auth_cookies.items():
            c.cookies.set(key, value)
        yield c


@pytest.fixture()
async def repo(test_db):
    return DocumentRepository(test_db)
