"""Shared fixtures for admin document API tests."""

from __future__ import annotations

import asyncio
import uuid
from datetime import UTC, datetime
from unittest.mock import AsyncMock, MagicMock

import pytest
from fastapi.testclient import TestClient

from app.config import Settings
from app.domain.document_service import DocumentService
from app.main import create_app
from app.storage.database import init_db
from app.storage.document_repo import DocumentRepository
from app.storage.models import DocumentRecord, DocumentStatus

TEST_API_KEY = "test-secret-key-12345"


def _make_record(**overrides) -> DocumentRecord:
    now = datetime.now(UTC)
    defaults = {
        "id": 0,  # Will be auto-generated by database
        "document_id": uuid.uuid4().hex,
        "filename": "test.docx",
        "title": "Test document",
        "s3_key": "documents/test.docx",
        "mime_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "size_bytes": 12345,
        "status": DocumentStatus.completed,
        "is_search_enabled": True,
        "error": None,
        "created_at": now,
        "updated_at": now,
        "indexed_at": now,
        "chunk_count": 5,
    }
    defaults.update(overrides)
    return DocumentRecord(**defaults)


# ── fixtures ──────────────────────────────────────────────────────


@pytest.fixture()
async def db_path(tmp_path):
    path = str(tmp_path / "test.db")
    await init_db(path)
    return path


@pytest.fixture()
def settings(db_path):
    return Settings(
        admin_api_key=TEST_API_KEY,
        db_path=db_path,
        s3_endpoint_url="http://localhost:9000",
        s3_access_key="minioadmin",
        s3_secret_key="minioadmin",
        s3_bucket="test-bucket",
        qdrant_url="http://localhost:6333",
        _env_file=None,
    )


@pytest.fixture()
def mock_qdrant():
    client = MagicMock()
    client.delete = MagicMock()
    client.set_payload = MagicMock()
    client.count = MagicMock(return_value=MagicMock(count=0))
    client.close = MagicMock()
    return client


@pytest.fixture()
def mock_embeddings():
    return MagicMock()


@pytest.fixture()
def mock_s3():
    """Mock S3Storage with async methods."""
    s3 = MagicMock()
    s3.upload = AsyncMock()
    s3.download = AsyncMock(return_value=b"file content here")
    s3.delete = AsyncMock()
    s3.exists = AsyncMock(return_value=False)
    s3.open = AsyncMock()
    s3.close = AsyncMock()
    return s3


@pytest.fixture()
def mock_qa_service():
    """Mock QAService with invalidate_document_chain_cache method."""
    qa = MagicMock()
    qa.invalidate_document_chain_cache = MagicMock()
    return qa


@pytest.fixture()
def app(settings, mock_qdrant, mock_embeddings, mock_s3, mock_qa_service, db_path):
    """Create a test app with mocked Qdrant, embeddings, S3, and QA service."""
    application = create_app(settings)

    # Override lifespan-initialised resources
    repo = DocumentRepository(db_path)
    service = DocumentService(
        repo=repo,
        qdrant_client=mock_qdrant,
        embeddings=mock_embeddings,
        collection_name="test_collection",
    )
    application.state.qdrant_client = mock_qdrant
    application.state.embeddings = mock_embeddings
    application.state.doc_repo = repo
    application.state.doc_service = service
    application.state.s3 = mock_s3
    application.state.indexing_semaphore = asyncio.Semaphore(2)
    application.state.qa_service = mock_qa_service

    return application


@pytest.fixture()
def client(app):
    return TestClient(app, raise_server_exceptions=False)


@pytest.fixture()
def auth_cookies():
    return {"admin_session": TEST_API_KEY}


@pytest.fixture()
def auth_client(app, auth_cookies):
    """Authenticated client with cookies set on the instance."""
    c = TestClient(app, raise_server_exceptions=False)
    for key, value in auth_cookies.items():
        c.cookies.set(key, value)
    return c


@pytest.fixture()
async def repo(db_path):
    return DocumentRepository(db_path)
