"""Tests for Block 12 — admin document API and HTML pages."""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from io import BytesIO
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from fastapi.testclient import TestClient

from app.config import Settings
from app.domain.document_service import DocumentService
from app.main import create_app
from app.storage.database import init_db
from app.storage.document_repo import DocumentRepository
from app.storage.models import DocumentRecord, DocumentStatus

TEST_API_KEY = "test-secret-key-12345"


# ── fixtures ──────────────────────────────────────────────────────


@pytest.fixture()
async def db_path(tmp_path):
    path = str(tmp_path / "test.db")
    await init_db(path)
    return path


@pytest.fixture()
def settings(db_path):
    return Settings(
        admin_api_key=TEST_API_KEY,
        db_path=db_path,
        s3_endpoint_url="http://localhost:9000",
        s3_access_key="minioadmin",
        s3_secret_key="minioadmin",
        s3_bucket="test-bucket",
        qdrant_url="http://localhost:6333",
    )


@pytest.fixture()
def mock_qdrant():
    client = MagicMock()
    client.delete = MagicMock()
    client.set_payload = MagicMock()
    client.count = MagicMock(return_value=MagicMock(count=0))
    client.close = MagicMock()
    return client


@pytest.fixture()
def mock_embeddings():
    return MagicMock()


@pytest.fixture()
def mock_s3():
    """Mock S3Storage with async methods."""
    s3 = MagicMock()
    s3.upload = AsyncMock()
    s3.download = AsyncMock(return_value=b"file content here")
    s3.delete = AsyncMock()
    s3.exists = AsyncMock(return_value=False)
    s3.open = AsyncMock()
    s3.close = AsyncMock()
    return s3


@pytest.fixture()
def app(settings, mock_qdrant, mock_embeddings, mock_s3, db_path):
    """Create a test app with mocked Qdrant, embeddings, and S3."""
    application = create_app(settings)

    # Override lifespan-initialised resources
    repo = DocumentRepository(db_path)
    service = DocumentService(
        repo=repo,
        qdrant_client=mock_qdrant,
        embeddings=mock_embeddings,
        collection_name="test_collection",
    )
    application.state.qdrant_client = mock_qdrant
    application.state.embeddings = mock_embeddings
    application.state.doc_repo = repo
    application.state.doc_service = service
    application.state.s3 = mock_s3

    return application


@pytest.fixture()
def client(app):
    return TestClient(app, raise_server_exceptions=False)


@pytest.fixture()
def auth_cookies():
    return {"admin_session": TEST_API_KEY}


@pytest.fixture()
def auth_client(app, auth_cookies):
    """Authenticated client with cookies set on the instance."""
    c = TestClient(app, raise_server_exceptions=False)
    for key, value in auth_cookies.items():
        c.cookies.set(key, value)
    return c


@pytest.fixture()
async def repo(db_path):
    return DocumentRepository(db_path)


def _make_record(**overrides) -> DocumentRecord:
    now = datetime.now(UTC)
    defaults = {
        "id": 0,  # Will be auto-generated by database
        "document_id": uuid.uuid4().hex,
        "filename": "test.docx",
        "title": "Test document",
        "s3_key": "documents/test.docx",
        "mime_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "size_bytes": 12345,
        "status": DocumentStatus.completed,
        "is_search_enabled": True,
        "error": None,
        "created_at": now,
        "updated_at": now,
        "indexed_at": now,
        "chunk_count": 5,
    }
    defaults.update(overrides)
    return DocumentRecord(**defaults)


# ── Auth tests ────────────────────────────────────────────────────


class TestAuth:
    def test_login_page_renders(self, client):
        resp = client.get("/login")
        assert resp.status_code == 200
        assert "HR-панель управления" in resp.text

    def test_login_with_valid_key(self, client):
        resp = client.post(
            "/login",
            data={"api_key": TEST_API_KEY},
            follow_redirects=False,
        )
        assert resp.status_code == 303
        assert resp.headers["location"] == "/documents"
        assert "admin_session" in resp.cookies

    def test_login_with_invalid_key(self, client):
        resp = client.post(
            "/login",
            data={"api_key": "wrong"},
            follow_redirects=False,
        )
        assert resp.status_code == 303
        assert "error=invalid_key" in resp.headers["location"]

    def test_documents_page_requires_auth(self, client):
        resp = client.get("/documents")
        assert resp.status_code == 403

    def test_api_requires_auth(self, client):
        resp = client.get("/api/documents")
        assert resp.status_code == 403

    def test_logout_clears_cookie(self, client, auth_cookies):
        resp = client.get("/logout", follow_redirects=False)
        assert resp.status_code == 303
        assert resp.headers["location"] == "/login"


# ── Documents page ────────────────────────────────────────────────


class TestDocumentsPage:
    def test_documents_page_renders(self, auth_client):
        resp = auth_client.get("/documents")
        assert resp.status_code == 200
        assert "Документы" in resp.text

    def test_documents_page_shows_empty_state(self, auth_client):
        resp = auth_client.get("/documents")
        assert resp.status_code == 200
        assert "Документов пока нет" in resp.text

    async def test_documents_page_shows_documents(
        self, auth_client, repo
    ):
        rec = _make_record()
        await repo.create(rec)
        resp = auth_client.get("/documents")
        assert resp.status_code == 200
        assert rec.title in resp.text


# ── List API ──────────────────────────────────────────────────────


class TestListDocuments:
    def test_empty_list(self, auth_client):
        resp = auth_client.get("/api/documents")
        assert resp.status_code == 200
        data = resp.json()
        assert data["items"] == []
        assert data["total"] == 0
        assert data["page"] == 1
        assert data["per_page"] == 10
        assert data["pages"] == 0

    async def test_returns_documents(self, auth_client, repo):
        rec = _make_record()
        await repo.create(rec)
        resp = auth_client.get("/api/documents")
        assert resp.status_code == 200
        data = resp.json()
        assert len(data["items"]) == 1
        assert data["items"][0]["document_id"] == rec.document_id
        assert data["items"][0]["title"] == rec.title
        assert data["total"] == 1
        assert data["page"] == 1
        assert data["per_page"] == 10
        assert data["pages"] == 1


# ── Get document ──────────────────────────────────────────────────


class TestGetDocument:
    async def test_get_existing(self, auth_client, repo):
        rec = _make_record()
        await repo.create(rec)
        resp = auth_client.get(
            f"/api/documents/{rec.document_id}"
        )
        assert resp.status_code == 200
        assert resp.json()["title"] == rec.title

    def test_get_nonexistent(self, auth_client):
        resp = auth_client.get("/api/documents/nonexistent")
        assert resp.status_code == 404


# ── Update title ──────────────────────────────────────────────────


class TestUpdateTitle:
    async def test_rename(self, auth_client, repo):
        rec = _make_record()
        await repo.create(rec)
        resp = auth_client.patch(
            f"/api/documents/{rec.document_id}/title",
            data={"title": "New Name"},
        )
        assert resp.status_code == 200
        assert resp.json()["title"] == "New Name"

    async def test_rename_empty_rejected(self, auth_client, repo):
        rec = _make_record()
        await repo.create(rec)
        resp = auth_client.patch(
            f"/api/documents/{rec.document_id}/title",
            data={"title": "   "},
        )
        assert resp.status_code == 422

    def test_rename_nonexistent(self, auth_client):
        resp = auth_client.patch(
            "/api/documents/nonexistent/title",
            data={"title": "x"},
        )
        assert resp.status_code == 404

    async def test_rename_htmx_returns_html(self, auth_client, repo):
        rec = _make_record()
        await repo.create(rec)
        resp = auth_client.patch(
            f"/api/documents/{rec.document_id}/title",
            data={"title": "HTMX Title"},
            headers={"HX-Request": "true"},
        )
        assert resp.status_code == 200
        assert "HTMX Title" in resp.text
        assert "<tr" in resp.text


# ── Toggle search ─────────────────────────────────────────────────


class TestToggleSearch:
    async def test_disable_search(self, auth_client, repo):
        rec = _make_record(is_search_enabled=True)
        await repo.create(rec)
        resp = auth_client.patch(
            f"/api/documents/{rec.document_id}/search",
            data={"enabled": "false"},
        )
        assert resp.status_code == 200
        assert resp.json()["is_search_enabled"] is False

    async def test_enable_search(self, auth_client, repo):
        rec = _make_record(is_search_enabled=False)
        await repo.create(rec)
        resp = auth_client.patch(
            f"/api/documents/{rec.document_id}/search",
            data={"enabled": "true"},
        )
        assert resp.status_code == 200
        assert resp.json()["is_search_enabled"] is True

    async def test_toggle_htmx_returns_html(self, auth_client, repo):
        rec = _make_record(is_search_enabled=True)
        await repo.create(rec)
        resp = auth_client.patch(
            f"/api/documents/{rec.document_id}/search",
            data={"enabled": "false"},
            headers={"HX-Request": "true"},
        )
        assert resp.status_code == 200
        assert "<tr" in resp.text


# ── Delete ────────────────────────────────────────────────────────


class TestDeleteDocument:
    async def test_delete_existing(self, auth_client, repo, mock_s3):
        rec = _make_record()
        await repo.create(rec)

        resp = auth_client.delete(
            f"/api/documents/{rec.document_id}"
        )
        assert resp.status_code == 200
        assert resp.json()["deleted"] is True

        # Verify deleted from repo
        fetched = await repo.get(rec.document_id)
        assert fetched is None

        # Verify S3 delete was called
        mock_s3.delete.assert_awaited_once_with(rec.s3_key)

    def test_delete_nonexistent(self, auth_client):
        resp = auth_client.delete(
            "/api/documents/nonexistent"
        )
        assert resp.status_code == 404

    async def test_delete_htmx_returns_empty(
        self, auth_client, repo, mock_s3
    ):
        rec = _make_record()
        await repo.create(rec)

        resp = auth_client.delete(
            f"/api/documents/{rec.document_id}",
            headers={"HX-Request": "true"},
        )
        assert resp.status_code == 200
        assert resp.text == ""


# ── Upload ────────────────────────────────────────────────────────


class TestUpload:
    @patch("app.api.documents.load_document", return_value=[])
    @patch("app.api.documents._index_in_background", new_callable=AsyncMock)
    async def test_upload_valid_file(
        self, mock_bg, mock_parse, auth_client, mock_s3
    ):
        fake_docx = BytesIO(b"PK\x03\x04fake docx content")
        resp = auth_client.post(
            "/api/documents/upload",
            files=[("files", ("test.docx", fake_docx, "application/octet-stream"))],
        )
        assert resp.status_code == 200
        data = resp.json()
        assert len(data["uploaded"]) == 1
        assert data["uploaded"][0]["filename"] == "test.docx"
        assert data["errors"] == []

        # Verify S3 upload was called
        mock_s3.upload.assert_awaited_once()

    def test_upload_rejects_non_docx(self, auth_client):
        resp = auth_client.post(
            "/api/documents/upload",
            files=[("files", ("test.pdf", BytesIO(b"fake"), "application/pdf"))],
        )
        assert resp.status_code == 200
        data = resp.json()
        assert len(data["uploaded"]) == 0
        assert len(data["errors"]) == 1
        assert "Unsupported" in data["errors"][0]["error"]

    def test_upload_rejects_empty_file(self, auth_client):
        resp = auth_client.post(
            "/api/documents/upload",
            files=[("files", ("empty.docx", BytesIO(b""), "application/octet-stream"))],
        )
        assert resp.status_code == 200
        data = resp.json()
        assert len(data["errors"]) == 1
        assert "Empty" in data["errors"][0]["error"]

    def test_upload_requires_auth(self, client):
        resp = client.post(
            "/api/documents/upload",
            files=[("files", ("test.docx", BytesIO(b"data"), "application/octet-stream"))],
        )
        assert resp.status_code == 403


# ── Partials ──────────────────────────────────────────────────────


class TestPartials:
    def test_table_partial_empty(self, auth_client):
        resp = auth_client.get("/partials/document-table")
        assert resp.status_code == 200
        assert "Документов пока нет" in resp.text

    async def test_table_partial_with_docs(self, auth_client, repo):
        rec = _make_record()
        await repo.create(rec)
        resp = auth_client.get("/partials/document-table")
        assert resp.status_code == 200
        assert rec.title in resp.text

    async def test_row_partial(self, auth_client, repo):
        rec = _make_record()
        await repo.create(rec)
        resp = auth_client.get(
            f"/partials/document-row/{rec.document_id}"
        )
        assert resp.status_code == 200
        assert rec.title in resp.text

    def test_row_partial_nonexistent(self, auth_client):
        resp = auth_client.get(
            "/partials/document-row/nonexistent"
        )
        assert resp.status_code == 200
        assert resp.text == ""

    def test_partials_require_auth(self, client):
        resp = client.get("/partials/document-table")
        assert resp.status_code == 403


# ── Download ──────────────────────────────────────────────────────


class TestDownload:
    async def test_download_existing(
        self, auth_client, repo, mock_s3
    ):
        rec = _make_record()
        await repo.create(rec)

        # S3 mock returns file content and reports file exists
        mock_s3.exists.return_value = True
        mock_s3.download.return_value = b"file content here"

        resp = auth_client.get(
            f"/api/documents/{rec.document_id}/download",
        )
        assert resp.status_code == 200
        assert resp.content == b"file content here"
        mock_s3.download.assert_awaited_once_with(rec.s3_key)

    def test_download_nonexistent(self, auth_client):
        resp = auth_client.get(
            "/api/documents/nonexistent/download"
        )
        assert resp.status_code == 404

    async def test_download_missing_file(
        self, auth_client, repo, mock_s3
    ):
        rec = _make_record()
        await repo.create(rec)

        # S3 reports file does not exist
        mock_s3.exists.return_value = False

        resp = auth_client.get(
            f"/api/documents/{rec.document_id}/download",
        )
        assert resp.status_code == 404


# ── Pagination ────────────────────────────────────────────────────


class TestPagination:
    async def test_list_paginated_defaults(self, auth_client, repo):
        """GET /api/documents with no params returns items with pagination metadata."""
        # Create 5 documents
        for i in range(5):
            rec = _make_record(document_id=f"doc-{i}", title=f"Document {i}")
            await repo.create(rec)

        resp = auth_client.get("/api/documents")
        assert resp.status_code == 200
        data = resp.json()

        assert len(data["items"]) == 5
        assert data["total"] == 5
        assert data["page"] == 1
        assert data["per_page"] == 10
        assert data["pages"] == 1

    async def test_list_paginated_with_params(self, auth_client, repo):
        """GET /api/documents?page=2&per_page=3 returns correct 3-item slice."""
        # Create 7 documents (ids will be 1-7, ordered by id DESC: 7,6,5,4,3,2,1)
        created_ids = []
        for i in range(7):
            rec = _make_record(document_id=f"doc-{i}", title=f"Document {i}")
            created = await repo.create(rec)
            created_ids.append(created.id)

        # Page 2 with per_page=3 should return items with ids 4, 3, 2 (0-indexed: positions 3,4,5)
        resp = auth_client.get("/api/documents?page=2&per_page=3")
        assert resp.status_code == 200
        data = resp.json()

        assert len(data["items"]) == 3
        assert data["total"] == 7
        assert data["page"] == 2
        assert data["per_page"] == 3
        assert data["pages"] == 3  # 7 items / 3 per page = 2.33 -> 3 pages

        # Verify correct items returned (ordered by id DESC)
        # Page 1: ids 7, 6, 5
        # Page 2: ids 4, 3, 2
        actual_ids = [item["document_id"] for item in data["items"]]
        assert actual_ids == ["doc-3", "doc-2", "doc-1"]

    async def test_list_paginated_total_count(self, auth_client, repo):
        """Verify total field matches actual document count."""
        # Create documents one by one and verify total
        for i in range(10):
            rec = _make_record(document_id=f"doc-{i}", title=f"Document {i}")
            await repo.create(rec)

            resp = auth_client.get("/api/documents")
            data = resp.json()
            assert data["total"] == i + 1

    async def test_list_paginated_beyond_range(self, auth_client, repo):
        """GET /api/documents?page=100&per_page=5 returns empty items but correct total."""
        # Create 7 documents
        for i in range(7):
            rec = _make_record(document_id=f"doc-{i}", title=f"Document {i}")
            await repo.create(rec)

        resp = auth_client.get("/api/documents?page=100&per_page=5")
        assert resp.status_code == 200
        data = resp.json()

        assert data["items"] == []
        assert data["total"] == 7
        assert data["page"] == 100
        assert data["per_page"] == 5
        assert data["pages"] == 2  # 7 items / 5 per page = 1.4 -> 2 pages

    async def test_document_table_partial_pagination(self, auth_client, repo):
        """GET /partials/document-table with HX-Request returns pagination controls."""
        # Create 7 documents to trigger pagination (more than default per_page would be,
        # but we use per_page=3 to ensure multiple pages)
        for i in range(7):
            rec = _make_record(document_id=f"doc-{i}", title=f"Document {i}")
            await repo.create(rec)

        resp = auth_client.get(
            "/partials/document-table?page=1&per_page=3",
            headers={"HX-Request": "true"}
        )
        assert resp.status_code == 200

        # Check for pagination-related class names
        assert "join" in resp.text  # Pagination container class
        assert "join-item" in resp.text  # Pagination button class
        assert "btn-active" in resp.text  # Active page button class

        # Check for page number buttons (should have pages 1, 2, 3 for 7 items with per_page=3)
        # Page links contain hx-get attributes with page numbers
        assert 'hx-get="/partials/document-table?page=1&per_page=3"' in resp.text
        assert 'hx-get="/partials/document-table?page=2&per_page=3"' in resp.text
        assert 'hx-get="/partials/document-table?page=3&per_page=3"' in resp.text


# ── Reindex ───────────────────────────────────────────────────────


class TestReindex:
    @patch("app.api.documents.load_document", return_value=[])
    async def test_reindex_starts(
        self, mock_parse, auth_client, repo, mock_s3
    ):
        rec = _make_record()
        await repo.create(rec)

        # S3 reports file exists
        mock_s3.exists.return_value = True

        resp = auth_client.post(
            f"/api/documents/{rec.document_id}/reindex",
        )
        assert resp.status_code == 200
        assert resp.json()["status"] == "reindexing"

    def test_reindex_nonexistent(self, auth_client):
        resp = auth_client.post(
            "/api/documents/nonexistent/reindex"
        )
        assert resp.status_code == 404

    async def test_reindex_missing_file(
        self, auth_client, repo, mock_s3
    ):
        rec = _make_record()
        await repo.create(rec)

        # S3 reports file does not exist
        mock_s3.exists.return_value = False

        resp = auth_client.post(
            f"/api/documents/{rec.document_id}/reindex",
        )
        assert resp.status_code == 404
        assert "storage" in resp.json()["detail"]
