"""Tests for app.storage — document metadata model, database init, and CRUD."""

from __future__ import annotations

import uuid
from datetime import UTC, datetime

import pytest
from databases import Database

from app.storage.database import init_db
from app.storage.document_repo import DocumentRepository
from app.storage.models import DocumentRecord, DocumentStatus

# ── helpers ───────────────────────────────────────────────────────


def _make_record(**overrides) -> DocumentRecord:
    """Build a ``DocumentRecord`` with sensible defaults.  Override any field."""
    now = datetime.now(UTC)
    defaults = {
        "id": 0,  # Will be auto-generated by database
        "document_id": uuid.uuid4().hex,
        "filename": "test.docx",
        "title": "Test document",
        "s3_key": "documents/test.docx",
        "mime_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "size_bytes": 12345,
        "status": DocumentStatus.pending,
        "is_search_enabled": True,
        "error": None,
        "created_at": now,
        "updated_at": now,
        "indexed_at": None,
        "chunk_count": 0,
    }
    defaults.update(overrides)
    return DocumentRecord(**defaults)


@pytest.fixture()
async def repo(pg_container):
    """Create a fresh PostgreSQL DB and return a DocumentRepository."""
    raw_url = pg_container.get_connection_url()
    # get_connection_url() returns postgresql+psycopg2://...
    # databases[asyncpg] needs postgresql://...
    url = raw_url.replace("postgresql+psycopg2", "postgresql")
    db = Database(url)
    await db.connect()
    # Clean tables before each test for isolation
    await db.execute(query="DROP TABLE IF EXISTS category_files CASCADE")
    await db.execute(query="DROP TABLE IF EXISTS documents CASCADE")
    await init_db(db)
    yield DocumentRepository(db)
    await db.disconnect()


# ── Model tests ──────────────────────────────────────────────────


class TestDocumentRecord:
    def test_default_status_is_pending(self):
        rec = _make_record()
        assert rec.status == DocumentStatus.pending

    def test_default_search_enabled(self):
        rec = _make_record()
        assert rec.is_search_enabled is True

    def test_default_chunk_count_zero(self):
        rec = _make_record()
        assert rec.chunk_count == 0

    def test_status_enum_values(self):
        assert DocumentStatus.pending.value == "pending"
        assert DocumentStatus.processing.value == "processing"
        assert DocumentStatus.completed.value == "completed"
        assert DocumentStatus.failed.value == "failed"


# ── Database init ────────────────────────────────────────────────


class TestInitDb:
    async def test_creates_database_tables(self, pg_container):
        raw_url = pg_container.get_connection_url()
        # get_connection_url() returns postgresql+psycopg2://...
        # databases[asyncpg] needs postgresql://...
        url = raw_url.replace("postgresql+psycopg2", "postgresql")
        db = Database(url)
        await db.connect()
        # Clean tables first
        await db.execute(query="DROP TABLE IF EXISTS category_files CASCADE")
        await db.execute(query="DROP TABLE IF EXISTS documents CASCADE")
        await init_db(db)
        # Verify documents table exists by querying it
        result = await db.fetch_one(
            query="SELECT table_name FROM information_schema.tables "
            "WHERE table_name='documents'"
        )
        assert result is not None
        assert result["table_name"] == "documents"
        await db.disconnect()

    async def test_idempotent(self, pg_container):
        raw_url = pg_container.get_connection_url()
        # get_connection_url() returns postgresql+psycopg2://...
        # databases[asyncpg] needs postgresql://...
        url = raw_url.replace("postgresql+psycopg2", "postgresql")
        db = Database(url)
        await db.connect()
        # Clean tables first
        await db.execute(query="DROP TABLE IF EXISTS category_files CASCADE")
        await db.execute(query="DROP TABLE IF EXISTS documents CASCADE")
        await init_db(db)
        await init_db(db)  # should not raise
        await db.disconnect()


# ── CRUD: create ─────────────────────────────────────────────────


class TestCreate:
    async def test_create_and_get(self, repo):
        rec = _make_record()
        created = await repo.create(rec)
        assert created.document_id == rec.document_id
        assert created.filename == "test.docx"

        fetched = await repo.get(rec.document_id)
        assert fetched is not None
        assert fetched.document_id == rec.document_id
        assert fetched.filename == "test.docx"

    async def test_create_sets_timestamps(self, repo):
        rec = _make_record()
        created = await repo.create(rec)
        assert created.created_at is not None
        assert created.updated_at is not None

    async def test_create_preserves_all_fields(self, repo):
        now = datetime.now(UTC)
        rec = _make_record(
            status=DocumentStatus.completed,
            is_search_enabled=False,
            error="some error",
            indexed_at=now,
            chunk_count=42,
        )
        created = await repo.create(rec)
        fetched = await repo.get(created.document_id)
        assert fetched is not None
        assert fetched.status == DocumentStatus.completed
        assert fetched.is_search_enabled is False
        assert fetched.error == "some error"
        assert fetched.indexed_at is not None
        assert fetched.chunk_count == 42


# ── CRUD: read ───────────────────────────────────────────────────


class TestRead:
    async def test_get_missing_returns_none(self, repo):
        result = await repo.get("nonexistent")
        assert result is None

    async def test_list_page_empty(self, repo):
        docs, total = await repo.list_page()
        assert docs == []
        assert total == 0

    async def test_list_page_returns_newest_first(self, repo):
        r1 = _make_record(document_id="aaa", title="First")
        r2 = _make_record(document_id="bbb", title="Second")
        await repo.create(r1)
        await repo.create(r2)
        docs, total = await repo.list_page()
        assert len(docs) == 2
        assert total == 2
        # newest first — r2 was created after r1 (higher id)
        assert docs[0].document_id == "bbb"
        assert docs[1].document_id == "aaa"

    async def test_list_page_pagination(self, repo):
        r1 = _make_record(document_id="aaa", title="First")
        r2 = _make_record(document_id="bbb", title="Second")
        r3 = _make_record(document_id="ccc", title="Third")
        await repo.create(r1)
        await repo.create(r2)
        await repo.create(r3)

        # Page 1, per_page=2
        docs, total = await repo.list_page(page=1, per_page=2)
        assert len(docs) == 2
        assert total == 3
        assert docs[0].document_id == "ccc"
        assert docs[1].document_id == "bbb"

        # Page 2, per_page=2
        docs, total = await repo.list_page(page=2, per_page=2)
        assert len(docs) == 1
        assert total == 3
        assert docs[0].document_id == "aaa"


# ── Filters & Sorting ─────────────────────────────────────────────


class TestListPageFilters:
    async def test_filter_by_status(self, repo):
        """list_page(status=...) returns only matching documents."""
        r1 = _make_record(document_id="a", status=DocumentStatus.pending)
        r2 = _make_record(document_id="b", status=DocumentStatus.completed)
        r3 = _make_record(document_id="c", status=DocumentStatus.failed)
        await repo.create(r1)
        await repo.create(r2)
        await repo.create(r3)

        docs, total = await repo.list_page(status="completed")
        assert total == 1
        assert docs[0].document_id == "b"

        docs, total = await repo.list_page(status="pending")
        assert total == 1
        assert docs[0].document_id == "a"

    async def test_filter_status_all_returns_everything(self, repo):
        """status='all' should not filter."""
        r1 = _make_record(document_id="a", status=DocumentStatus.pending)
        r2 = _make_record(document_id="b", status=DocumentStatus.completed)
        await repo.create(r1)
        await repo.create(r2)

        docs, total = await repo.list_page(status="all")
        assert total == 2

    async def test_filter_source_type_docx(self, repo):
        """source_type='docx' returns only .docx files."""
        r1 = _make_record(document_id="a", filename="report.docx")
        r2 = _make_record(document_id="b", filename="memo.doc")
        r3 = _make_record(document_id="c", filename="notes.txt")
        await repo.create(r1)
        await repo.create(r2)
        await repo.create(r3)

        docs, total = await repo.list_page(source_type="docx")
        assert total == 1
        assert docs[0].document_id == "a"

    async def test_filter_source_type_doc(self, repo):
        """source_type='doc' returns .doc but not .docx."""
        r1 = _make_record(document_id="a", filename="report.docx")
        r2 = _make_record(document_id="b", filename="memo.doc")
        r3 = _make_record(document_id="c", filename="notes.txt")
        await repo.create(r1)
        await repo.create(r2)
        await repo.create(r3)

        docs, total = await repo.list_page(source_type="doc")
        assert total == 1
        assert docs[0].document_id == "b"

    async def test_filter_source_type_other(self, repo):
        """source_type='other' excludes .doc and .docx."""
        r1 = _make_record(document_id="a", filename="report.docx")
        r2 = _make_record(document_id="b", filename="memo.doc")
        r3 = _make_record(document_id="c", filename="notes.txt")
        await repo.create(r1)
        await repo.create(r2)
        await repo.create(r3)

        docs, total = await repo.list_page(source_type="other")
        assert total == 1
        assert docs[0].document_id == "c"

    async def test_sort_by_title_asc(self, repo):
        """sort_field='title', sort_dir='asc' orders alphabetically."""
        r1 = _make_record(document_id="a", title="Banana")
        r2 = _make_record(document_id="b", title="Apple")
        r3 = _make_record(document_id="c", title="Cherry")
        await repo.create(r1)
        await repo.create(r2)
        await repo.create(r3)

        docs, total = await repo.list_page(
            sort_field="title", sort_dir="asc",
        )
        assert total == 3
        assert [d.title for d in docs] == ["Apple", "Banana", "Cherry"]

    async def test_sort_by_title_desc(self, repo):
        """sort_field='title', sort_dir='desc' orders reverse-alphabetically."""
        r1 = _make_record(document_id="a", title="Banana")
        r2 = _make_record(document_id="b", title="Apple")
        r3 = _make_record(document_id="c", title="Cherry")
        await repo.create(r1)
        await repo.create(r2)
        await repo.create(r3)

        docs, total = await repo.list_page(
            sort_field="title", sort_dir="desc",
        )
        assert total == 3
        assert [d.title for d in docs] == ["Cherry", "Banana", "Apple"]

    async def test_combined_status_and_sort(self, repo):
        """Combining status filter with sort works correctly."""
        r1 = _make_record(
            document_id="a", title="Zebra", status=DocumentStatus.completed,
        )
        r2 = _make_record(
            document_id="b", title="Alpha", status=DocumentStatus.completed,
        )
        r3 = _make_record(
            document_id="c", title="Mid", status=DocumentStatus.pending,
        )
        await repo.create(r1)
        await repo.create(r2)
        await repo.create(r3)

        docs, total = await repo.list_page(
            status="completed", sort_field="title", sort_dir="asc",
        )
        assert total == 2
        assert [d.title for d in docs] == ["Alpha", "Zebra"]


# ── CRUD: update ─────────────────────────────────────────────────


class TestUpdate:
    async def test_update_title(self, repo):
        rec = _make_record()
        await repo.create(rec)
        updated = await repo.update(rec.document_id, title="New title")
        assert updated is not None
        assert updated.title == "New title"

    async def test_update_status(self, repo):
        rec = _make_record()
        await repo.create(rec)
        updated = await repo.update(rec.document_id, status=DocumentStatus.processing)
        assert updated is not None
        assert updated.status == DocumentStatus.processing

    async def test_update_error_to_value(self, repo):
        rec = _make_record()
        await repo.create(rec)
        updated = await repo.update(rec.document_id, error="parse failed")
        assert updated is not None
        assert updated.error == "parse failed"

    async def test_update_error_to_none(self, repo):
        rec = _make_record(error="old error")
        await repo.create(rec)
        updated = await repo.update(rec.document_id, error=None)
        assert updated is not None
        assert updated.error is None

    async def test_update_chunk_count_and_indexed_at(self, repo):
        rec = _make_record()
        await repo.create(rec)
        now = datetime.now(UTC)
        updated = await repo.update(rec.document_id, chunk_count=15, indexed_at=now)
        assert updated is not None
        assert updated.chunk_count == 15
        assert updated.indexed_at is not None

    async def test_update_bumps_updated_at(self, repo):
        rec = _make_record()
        created = await repo.create(rec)
        updated = await repo.update(rec.document_id, title="Changed")
        assert updated is not None
        assert updated.updated_at >= created.updated_at

    async def test_update_nonexistent_returns_none(self, repo):
        result = await repo.update("nonexistent", title="x")
        assert result is None

    async def test_update_no_fields_returns_current(self, repo):
        rec = _make_record()
        await repo.create(rec)
        result = await repo.update(rec.document_id)
        assert result is not None
        assert result.document_id == rec.document_id


# ── CRUD: toggle_search ──────────────────────────────────────────


class TestToggleSearch:
    async def test_disable_search(self, repo):
        rec = _make_record(is_search_enabled=True)
        await repo.create(rec)
        toggled = await repo.toggle_search(rec.document_id, enabled=False)
        assert toggled is not None
        assert toggled.is_search_enabled is False

    async def test_enable_search(self, repo):
        rec = _make_record(is_search_enabled=False)
        await repo.create(rec)
        toggled = await repo.toggle_search(rec.document_id, enabled=True)
        assert toggled is not None
        assert toggled.is_search_enabled is True

    async def test_toggle_does_not_change_status(self, repo):
        rec = _make_record(status=DocumentStatus.completed)
        await repo.create(rec)
        toggled = await repo.toggle_search(rec.document_id, enabled=False)
        assert toggled is not None
        assert toggled.status == DocumentStatus.completed

    async def test_toggle_bumps_updated_at(self, repo):
        rec = _make_record()
        created = await repo.create(rec)
        toggled = await repo.toggle_search(rec.document_id, enabled=False)
        assert toggled is not None
        assert toggled.updated_at >= created.updated_at

    async def test_toggle_nonexistent_returns_none(self, repo):
        result = await repo.toggle_search("nonexistent", enabled=False)
        assert result is None


# ── CRUD: delete ─────────────────────────────────────────────────


class TestDelete:
    async def test_delete_existing(self, repo):
        rec = _make_record()
        await repo.create(rec)
        deleted = await repo.delete(rec.document_id)
        assert deleted is True
        assert await repo.get(rec.document_id) is None

    async def test_delete_nonexistent(self, repo):
        deleted = await repo.delete("nonexistent")
        assert deleted is False

    async def test_delete_does_not_affect_others(self, repo):
        r1 = _make_record(document_id="keep")
        r2 = _make_record(document_id="remove")
        await repo.create(r1)
        await repo.create(r2)
        await repo.delete("remove")
        remaining, total = await repo.list_page()
        assert len(remaining) == 1
        assert total == 1
        assert remaining[0].document_id == "keep"
