"""Document lifecycle service — orchestrates metadata, vector chunks, and file storage.

This is the central domain service for document management.  It coordinates
between the SQLite metadata repository, the Qdrant vector store, and
(optionally) file storage.  Route handlers and scripts delegate here instead
of implementing business logic themselves.
"""

from __future__ import annotations

import logging
import uuid
from collections.abc import Awaitable, Callable
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

from cafetera_admin.indexer import (
    delete_document_chunks,
    index_chunks,
    optimize_collection,
    prepare_chunks,
    set_search_enabled,
)
from cafetera_core.config import build_indexing_config
from cafetera_core.storage.models import DocumentRecord, DocumentStatus

if TYPE_CHECKING:
    from langchain_core.documents import Document as LCDocument
    from langchain_core.embeddings import Embeddings
    from qdrant_client import AsyncQdrantClient

    from cafetera_core.config import CoreSettings
    from cafetera_core.storage.document_repo import DocumentRepository
    from cafetera_core.storage.s3 import S3Storage

logger = logging.getLogger(__name__)


class DocumentService:
    """Manages the full lifecycle of a document in the knowledge base.

    Dependencies are injected via the constructor so the service is testable
    and independent of any particular transport layer.
    """

    def __init__(
        self,
        repo: DocumentRepository,
        qdrant_client: AsyncQdrantClient,
        embeddings: Embeddings,
        collection_name: str = "hr_documents",
        sparse_embedding: object | None = None,
        settings: CoreSettings | None = None,
    ) -> None:
        self._repo = repo
        self._qdrant = qdrant_client
        self._embeddings = embeddings
        self._collection = collection_name
        self._sparse_embedding = sparse_embedding
        self._settings = settings

    # ── S3 key helpers ─────────────────────────────────────────────

    async def generate_unique_s3_key(
        self,
        base_key: str,
        s3: S3Storage,
    ) -> str:
        """Return *base_key* if it doesn't exist in S3, otherwise append ``_1``, ``_2``, etc."""
        s3_key = base_key
        counter = 1
        while await s3.exists(s3_key):
            stem = Path(base_key).stem
            ext = Path(base_key).suffix
            parent = str(Path(base_key).parent)
            s3_key = f"{parent}/{stem}_{counter}{ext}"
            counter += 1
        return s3_key

    # ── create ────────────────────────────────────────────────────

    async def create_document(
        self,
        *,
        filename: str,
        title: str,
        s3_key: str,
        mime_type: str,
        size_bytes: int,
    ) -> DocumentRecord:
        """Register a new document in the metadata store (status=pending)."""
        now = datetime.now(UTC)
        record = DocumentRecord(
            id=0,  # Will be auto-generated by database
            document_id=uuid.uuid4().hex,
            filename=filename,
            title=title,
            s3_key=s3_key,
            mime_type=mime_type,
            size_bytes=size_bytes,
            status=DocumentStatus.pending,
            is_search_enabled=True,
            created_at=now,
            updated_at=now,
        )
        return await self._repo.create(record)

    # ── index ─────────────────────────────────────────────────────

    async def index_document(
        self,
        document_id: str,
        chunks: list[LCDocument],
    ) -> DocumentRecord | None:
        """Index parsed chunks for a document in Qdrant and update metadata.

        Transitions the document through ``processing`` → ``completed``
        (or ``failed`` on error).  Returns the updated record.
        """
        record = await self._repo.get(document_id)
        if record is None:
            return None

        await self._repo.update(
            document_id, status=DocumentStatus.processing, error=None
        )

        try:
            enriched = prepare_chunks(
                chunks,
                document_id=document_id,
                filename=record.filename,
                s3_key=record.s3_key,
                is_search_enabled=record.is_search_enabled,
            )
            count = await index_chunks(
                self._qdrant,
                self._embeddings,
                self._collection,
                enriched,
                sparse_embedding=self._sparse_embedding,
                batch_size=self._settings.qdrant_upsert_batch_size
                if self._settings
                else 64,
            )

            # Merge segments to reduce BM25 storage overhead
            try:
                await optimize_collection(self._qdrant, self._collection)
            except Exception:
                logger.warning(
                    "Post-index optimization failed for '%s'",
                    self._collection,
                    exc_info=True,
                )

            return await self._repo.update(
                document_id,
                status=DocumentStatus.completed,
                chunk_count=count,
                indexed_at=datetime.now(UTC),
                error=None,
                indexing_config=(
                    build_indexing_config(self._settings)
                    if self._settings
                    else None
                ),
            )
        except Exception as exc:
            logger.error(
                "Indexing failed for document %s", document_id, exc_info=True
            )
            await self._repo.update(
                document_id,
                status=DocumentStatus.failed,
                error=str(exc),
            )
            return await self._repo.get(document_id)

    # ── update metadata ───────────────────────────────────────────

    async def update_metadata(
        self,
        document_id: str,
        *,
        title: str | None = None,
    ) -> DocumentRecord | None:
        """Update editable document metadata fields."""
        return await self._repo.update(document_id, title=title)

    # ── toggle search ─────────────────────────────────────────────

    async def toggle_search(
        self,
        document_id: str,
        *,
        enabled: bool,
    ) -> DocumentRecord | None:
        """Toggle document participation in RAG retrieval.

        Updates both SQLite metadata (source of truth) and Qdrant chunk
        payloads.  The file and metadata are preserved regardless.
        """
        record = await self._repo.get(document_id)
        if record is None:
            return None

        # Update Qdrant chunks first to ensure consistency
        try:
            await set_search_enabled(
                self._qdrant,
                self._collection,
                document_id,
                enabled=enabled,
            )
        except Exception:
            logger.warning(
                "Failed to update Qdrant chunks for document %s",
                document_id,
                exc_info=True,
            )
            # Do not update SQLite if Qdrant failed — keep state consistent
            return record

        # Update SQLite only if Qdrant succeeded
        return await self._repo.toggle_search(document_id, enabled)

    # ── reindex ───────────────────────────────────────────────────

    async def reindex_document(
        self,
        document_id: str,
        chunks: list[LCDocument],
    ) -> DocumentRecord | None:
        """Re-index a document: delete old chunks, then index fresh ones.

        The caller is responsible for parsing the file into *chunks*
        (e.g. by downloading from MinIO and running the docx splitter).

        After successful reindexing the document is always restored to
        ``completed`` with ``is_search_enabled=True`` (handles the
        ``stale`` -> ``completed`` transition).
        """
        record = await self._repo.get(document_id)
        if record is None:
            return None

        await self._repo.update(
            document_id, status=DocumentStatus.processing, error=None
        )

        try:
            await delete_document_chunks(self._qdrant, self._collection, document_id)

            # Always index with is_search_enabled=True — fresh chunks are valid.
            enriched = prepare_chunks(
                chunks,
                document_id=document_id,
                filename=record.filename,
                s3_key=record.s3_key,
                is_search_enabled=True,
            )
            count = await index_chunks(
                self._qdrant,
                self._embeddings,
                self._collection,
                enriched,
                sparse_embedding=self._sparse_embedding,
                batch_size=self._settings.qdrant_upsert_batch_size
                if self._settings
                else 64,
            )

            # Merge segments to reduce BM25 storage overhead
            try:
                await optimize_collection(self._qdrant, self._collection)
            except Exception:
                logger.warning(
                    "Post-reindex optimization failed for '%s'",
                    self._collection,
                    exc_info=True,
                )

            # Atomically set status + is_search_enabled so the UI never
            # sees completed with is_search_enabled=False.
            return await self._repo.update(
                document_id,
                status=DocumentStatus.completed,
                is_search_enabled=True,
                chunk_count=count,
                indexed_at=datetime.now(UTC),
                error=None,
                indexing_config=(
                    build_indexing_config(self._settings)
                    if self._settings
                    else None
                ),
            )
        except Exception as exc:
            logger.error(
                "Reindexing failed for document %s", document_id, exc_info=True
            )
            await self._repo.update(
                document_id,
                status=DocumentStatus.failed,
                error=str(exc),
            )
            return await self._repo.get(document_id)

    # ── delete ────────────────────────────────────────────────────

    async def get_active_and_recent_documents(
        self,
        recent_seconds: int = 10,
    ) -> tuple[list[DocumentRecord], list[DocumentRecord]]:
        """Return (active_docs, all_docs_to_render) for status polling.

        *active_docs* are documents with pending/processing status.
        *all_docs_to_render* combines active docs with recently finished
        ones (completed/failed within *recent_seconds*), deduplicated.
        """
        pending_docs, _ = await self._repo.list_page(
            page=1, per_page=1000, status="pending"
        )
        processing_docs, _ = await self._repo.list_page(
            page=1, per_page=1000, status="processing"
        )
        active_docs = pending_docs + processing_docs

        recently_finished = await self._repo.list_recently_finished(
            seconds=recent_seconds
        )

        seen_ids = {doc.document_id for doc in active_docs}
        all_docs_to_render = active_docs + [
            doc for doc in recently_finished if doc.document_id not in seen_ids
        ]
        return active_docs, all_docs_to_render

    async def has_active_documents(self) -> bool:
        """Return ``True`` if any document has pending or processing status."""
        pending, _ = await self._repo.list_page(
            page=1, per_page=1, status="pending"
        )
        if pending:
            return True
        processing, _ = await self._repo.list_page(
            page=1, per_page=1, status="processing"
        )
        return len(processing) > 0

    async def delete_document(
        self,
        document_id: str,
        *,
        file_deleter: Callable[[str], Awaitable[None]] | None = None,
    ) -> bool:
        """Fully delete a document: metadata, Qdrant chunks, and optionally the file.

        Args:
            document_id: The document to delete.
            file_deleter: Optional async callable that removes the file by
                ``s3_key``.  Pass ``storage.delete`` when S3Storage is
                available.

        Returns:
            ``True`` if the document existed and was deleted.
        """
        record = await self._repo.get(document_id)
        if record is None:
            return False

        # Delete Qdrant chunks
        try:
            await delete_document_chunks(self._qdrant, self._collection, document_id)
        except Exception:
            logger.warning(
                "Failed to delete Qdrant chunks for document %s",
                document_id,
                exc_info=True,
            )

        # Delete file from storage (if deleter provided)
        if file_deleter is not None:
            try:
                await file_deleter(record.s3_key)
            except Exception:
                logger.warning(
                    "Failed to delete file %s for document %s",
                    record.s3_key,
                    document_id,
                    exc_info=True,
                )

        # Delete metadata (last step — source of truth)
        return await self._repo.delete(document_id)
