"""Document lifecycle service — orchestrates metadata, file storage, and RAG indexing.

This is the central domain service for document management.  It coordinates
between the PostgreSQL metadata repository, the RAG service (via RAGClient),
and (optionally) file storage.  Route handlers and scripts delegate here
instead of implementing business logic themselves.
"""

from __future__ import annotations

import logging
import uuid
from collections.abc import Awaitable, Callable
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

from cafetera_core.storage.models import DocumentRecord, DocumentStatus

if TYPE_CHECKING:
    from cafetera_core.rag_client import RAGClient
    from cafetera_core.storage.document_repo import DocumentRepository
    from cafetera_core.storage.s3 import S3Storage

logger = logging.getLogger(__name__)


class DocumentService:
    """Manages the full lifecycle of a document in the knowledge base.

    Dependencies are injected via the constructor so the service is testable
    and independent of any particular transport layer.
    """

    def __init__(
        self,
        repo: DocumentRepository,
        rag_client: RAGClient,
    ) -> None:
        self._repo = repo
        self._rag_client = rag_client

    # ── S3 key helpers ─────────────────────────────────────────────

    async def generate_unique_s3_key(
        self,
        base_key: str,
        s3: S3Storage,
    ) -> str:
        """Return *base_key* if it doesn't exist in S3, otherwise append ``_1``, ``_2``, etc."""
        s3_key = base_key
        counter = 1
        while await s3.exists(s3_key):
            stem = Path(base_key).stem
            ext = Path(base_key).suffix
            parent = str(Path(base_key).parent)
            s3_key = f"{parent}/{stem}_{counter}{ext}"
            counter += 1
        return s3_key

    # ── create ────────────────────────────────────────────────────

    async def create_document(
        self,
        *,
        filename: str,
        title: str,
        s3_key: str,
        mime_type: str,
        size_bytes: int,
    ) -> DocumentRecord:
        """Register a new document in the metadata store (status=pending)."""
        now = datetime.now(UTC)
        record = DocumentRecord(
            id=0,  # Will be auto-generated by database
            document_id=uuid.uuid4().hex,
            filename=filename,
            title=title,
            s3_key=s3_key,
            mime_type=mime_type,
            size_bytes=size_bytes,
            status=DocumentStatus.pending,
            is_search_enabled=True,
            created_at=now,
            updated_at=now,
        )
        return await self._repo.create(record)

    # ── index ─────────────────────────────────────────────────────

    async def index_document(
        self,
        document_id: str,
    ) -> DocumentRecord | None:
        """Index a document via the RAG service (full ingest) and update metadata.

        Transitions the document through ``processing`` → ``completed``
        (or ``failed`` on error).  Returns the updated record.
        """
        record = await self._repo.get(document_id)
        if record is None:
            return None

        await self._repo.update(
            document_id, status=DocumentStatus.processing, error=None
        )

        try:
            result = await self._rag_client.ingest_document(
                document_id=document_id,
                filename=record.filename,
                s3_key=record.s3_key,
                is_search_enabled=record.is_search_enabled,
            )

            indexing_config = {
                "page_count": result["page_count"],
                "binary_hash": result["binary_hash"],
                "extracted_title": result["extracted_title"],
            }

            return await self._repo.update(
                document_id,
                status=DocumentStatus.completed,
                chunk_count=result["chunks_indexed"],
                indexed_at=datetime.now(UTC),
                error=None,
                indexing_config=indexing_config,
            )
        except Exception as exc:
            logger.error(
                "Indexing failed for document %s", document_id, exc_info=True
            )
            await self._repo.update(
                document_id,
                status=DocumentStatus.failed,
                error=str(exc),
            )
            return await self._repo.get(document_id)

    # ── update metadata ───────────────────────────────────────────

    async def update_metadata(
        self,
        document_id: str,
        *,
        title: str | None = None,
    ) -> DocumentRecord | None:
        """Update editable document metadata fields."""
        return await self._repo.update(document_id, title=title)

    # ── toggle search ─────────────────────────────────────────────

    async def toggle_search(
        self,
        document_id: str,
        *,
        enabled: bool,
    ) -> DocumentRecord | None:
        """Toggle document participation in RAG retrieval.

        Updates Qdrant chunk payloads via the RAG service, then updates
        PostgreSQL metadata (source of truth).
        """
        record = await self._repo.get(document_id)
        if record is None:
            return None

        # Update Qdrant payload via RAG service
        await self._rag_client.toggle_search(document_id, is_search_enabled=enabled)

        return await self._repo.toggle_search(document_id, enabled)

    # ── reindex ───────────────────────────────────────────────────

    async def reindex_document(
        self,
        document_id: str,
    ) -> DocumentRecord | None:
        """Re-index a document via the RAG service (full ingest).

        The RAG service handles: delete old chunks → download from S3 →
        parse → chunk → embed → index.  After successful reindexing the
        document is restored to ``completed`` with ``is_search_enabled=True``.
        """
        record = await self._repo.get(document_id)
        if record is None:
            return None

        await self._repo.update(
            document_id, status=DocumentStatus.processing, error=None
        )

        try:
            result = await self._rag_client.ingest_document(
                document_id=document_id,
                filename=record.filename,
                s3_key=record.s3_key,
                is_search_enabled=True,
            )

            indexing_config = {
                "page_count": result["page_count"],
                "binary_hash": result["binary_hash"],
                "extracted_title": result["extracted_title"],
            }

            return await self._repo.update(
                document_id,
                status=DocumentStatus.completed,
                is_search_enabled=True,
                chunk_count=result["chunks_indexed"],
                indexed_at=datetime.now(UTC),
                error=None,
                indexing_config=indexing_config,
            )
        except Exception as exc:
            logger.error(
                "Reindexing failed for document %s", document_id, exc_info=True
            )
            await self._repo.update(
                document_id,
                status=DocumentStatus.failed,
                error=str(exc),
            )
            return await self._repo.get(document_id)

    # ── status helpers ────────────────────────────────────────────

    async def get_active_and_recent_documents(
        self,
        recent_seconds: int = 10,
    ) -> tuple[list[DocumentRecord], list[DocumentRecord]]:
        """Return (active_docs, all_docs_to_render) for status polling.

        *active_docs* are documents with pending/processing status.
        *all_docs_to_render* combines active docs with recently finished
        ones (completed/failed within *recent_seconds*), deduplicated.
        """
        pending_docs, _ = await self._repo.list_page(
            page=1, per_page=1000, status="pending"
        )
        processing_docs, _ = await self._repo.list_page(
            page=1, per_page=1000, status="processing"
        )
        active_docs = pending_docs + processing_docs

        recently_finished = await self._repo.list_recently_finished(
            seconds=recent_seconds
        )

        seen_ids = {doc.document_id for doc in active_docs}
        all_docs_to_render = active_docs + [
            doc for doc in recently_finished if doc.document_id not in seen_ids
        ]
        return active_docs, all_docs_to_render

    async def has_active_documents(self) -> bool:
        """Return ``True`` if any document has pending or processing status."""
        pending, _ = await self._repo.list_page(
            page=1, per_page=1, status="pending"
        )
        if pending:
            return True
        processing, _ = await self._repo.list_page(
            page=1, per_page=1, status="processing"
        )
        return len(processing) > 0

    # ── delete ────────────────────────────────────────────────────

    async def delete_document(
        self,
        document_id: str,
        *,
        file_deleter: Callable[[str], Awaitable[None]] | None = None,
    ) -> bool:
        """Fully delete a document: metadata, RAG chunks, and optionally the file.

        Args:
            document_id: The document to delete.
            file_deleter: Optional async callable that removes the file by
                ``s3_key``.  Pass ``storage.delete`` when S3Storage is
                available.

        Returns:
            ``True`` if the document existed and was deleted.
        """
        record = await self._repo.get(document_id)
        if record is None:
            return False

        # Delete RAG chunks via RAG service
        try:
            await self._rag_client.delete_document(document_id)
        except Exception:
            logger.warning(
                "Failed to delete RAG chunks for document %s",
                document_id,
                exc_info=True,
            )

        # Delete file from storage (if deleter provided)
        if file_deleter is not None:
            try:
                await file_deleter(record.s3_key)
            except Exception:
                logger.warning(
                    "Failed to delete file %s for document %s",
                    record.s3_key,
                    document_id,
                    exc_info=True,
                )

        # Delete metadata (last step — source of truth)
        return await self._repo.delete(document_id)

